### ISSUE TITLE
some problems about usage

### ISSUE THREAD

**Issue by 645873229** [javiribera/locating-objects-without-bboxes#12]
usage: train.py [-h] --train-dir TRAIN_DIR [--val-dir VAL_DIR] [--imgsize HxW]
                [--batch-size N] [--epochs N] [--nThreads N] [--lr LR] [-p P]
                [--no-cuda] [--no-data-augm] [--drop-last-batch] [--seed S]
                [--resume PATH] [--save PATH] [--log-interval N]
                [--max-trainset-size N] [--max-valset-size N] [--val-freq F]
                [--visdom-env NAME] [--visdom-server SRV] [--visdom-port PRT]
                [--optimizer OPTIM] [--replace-optimizer] [--max-mask-pts M]
                [--paint] [--radius R] [--n-points N] [--ultrasmallnet]
                [--lambdaa L]
train.py: error: unrecognized arguments: --env-name sorghum

code have no argument name "--env-name",but you  write it in your example

**Comment by javiribera** [comment]
You are right. I updated the example in the README to match the argparse.
https://github.com/javiribera/locating-objects-without-bboxes/commit/fcbead6d5dff98b5d377169e7b105c66a458b1ea should fix this
