### ISSUE TITLE
questions about the Hausdorff loss

### ISSUE THREAD

**Issue by kkhuang1990** [javiribera/locating-objects-without-bboxes#2]
thank you very much for sharing the codes.

I have some questions about the Averaged Hausdorff Loss. currently i am trying to solve a boundary detection problem based on medical image dataset. I tried to use your codes for AveragedHausdorffLoss, however inputs of your function are two point sets while my inputs are 2-class softmax probability map and ground truth labels.  The critical issue here is that  I have to calculate set1 from the probability map using torch.max() while the torch.max() function is not differentiable and thus not able to be pack-propagated. 

My question is do u know some methods to avoid the 'not being able to be back-propagated' problem or other implementations which directly use the prob map to calculate loss.

Best regards!

**Comment by JunMa11** [comment]
Hi @John1231983 ,
have you got some gain using whd loss for the binary segmentation?

**Comment by John1231983** [comment]
@JunMa11 : Not improve in my case. Hope you can have some improvement

**Comment by javiribera** [comment]
The WHD is not intended for binary segmentation. In that case the non-zero values in the label mask occupy a lot of pixels in the image, so a pixelwise loss (e.g L2) is more appropriate. So it's an expected behavior.
