### ISSUE TITLE
Can weighted Hausdorff distance be implemented into Semantic Segmentation task? 

### ISSUE THREAD

**Issue by MengzhangLI** [javiribera/locating-objects-without-bboxes#20]
Hi, very excited reading your paper and code.
The loss function containing weighted Hausdorff distance was designed for object detection task in this paper, can weighted Hausdorff distance be directly introduced into semantic segmentation task?

Thank you very much!

**Comment by javiribera** [comment]
I am not aware of any work using the WHD for anything besides object location, but if you know of anyone let me know. It seems you are not the first one to think about this, though. See https://github.com/javiribera/locating-objects-without-bboxes/issues/2#issuecomment-485556024

In any case, that would be interesting but it wouldn't fit into this github repository.

**Comment by MengzhangLI** [comment]
> I am not aware of any work using the WHD for anything besides object location, but if you know of anyone let me know. It seems you are not the first one to think about this, though. See [#2 (comment)](https://github.com/javiribera/locating-objects-without-bboxes/issues/2#issuecomment-485556024)
> 
> In any case, that would be interesting but it wouldn't fit into this github repository.

Hi, I'll read this issue. 
Thanks for your reply.
