### ISSUE TITLE
how to test images without gt

### ISSUE THREAD

**Issue by JiangAndy** [javiribera/locating-objects-without-bboxes#29]
After I have trained my model, how can I test my model, I only have images without gt(csv or xml).Thank you!

**Comment by JiangAndy** [comment]
I have solved it! I make a gt.csv,like following:
`filename,count,locations
img1.png,0,"[()]"
img2.png,0,"[()]"`

then I add some limits in data.py (class CSVDataset:), add a line  **if self.there_is_gt** in where 'locations' or 'count' are mentioned, because we don't have gts about there images.

![1](https://user-images.githubusercontent.com/28260554/81041479-839acc00-8ee0-11ea-8edf-80fca2cbe1ae.JPG)
![image](https://user-images.githubusercontent.com/28260554/81041611-d96f7400-8ee0-11ea-9fc8-53bb14587189.png)

**Comment by javiribera** [comment]
Thank you! I believe I solved it with commit d8485608c2625d675e61dfd692da675e8dde4225


For the record, this situation was intended to be solved with the --evaluate option (actually NOT using --evaluate). So the idea is if you don't have grounf truth, then you cannot evaluate metrics but you can store the output. But I confirm that not using --evaluate when not having any GT file was crashing. Now that commit fixes it.
