### ISSUE TITLE
did not find used-for-cvpr2019-submission

### ISSUE THREAD

**Issue by huitang** [javiribera/locating-objects-without-bboxes#3]
Hi there I did not find a repo with tag used-for-cvpr2019-submission

**Comment by huitang** [comment]
And do you mind to give an example of the CSV file ? thanks

**Comment by javiribera** [comment]
Hi @huitang, I forgot to push the used-for-cvpr2019-submission tag, but I just pushed it. Thanks for the heads up. Also you can find a CSV example file here: https://engineering.purdue.edu/~sorghum/dataset-plant-centers-2016
