### ISSUE TITLE
weird error

### ISSUE THREAD

**Issue by edrti** [javiribera/locating-objects-without-bboxes#31]
Hi,
I am using this commit version: commit d8485608c2625d675e61dfd692da675e8dde4225

I tried to train using this train command:  python -m object-locator.train  --train-dir real_train  --batch-size 32  --visdom-env mytrainingsession  --visdom-server localhost  --lr 1e-3  --val-dir real_train  --optim Adam  --save saved_model.ckpt

got this error:
https://pastebin.com/JMbjWZPn

i attached the gt.csv file
[gt.xlsx](https://github.com/javiribera/locating-objects-without-bboxes/files/4707593/gt.xlsx)

thanks in advance!

**Comment by edrti** [comment]
fixed :)

**Comment by javiribera** [comment]
It'd be great if you could share how you fixed it! Thanks
