### ISSUE TITLE
validation time

### ISSUE THREAD

**Issue by teeinn** [javiribera/locating-objects-without-bboxes#35]
I know there's been many issues related with validation time.
But to me, it's not clear.

I am training mall dataset and set --taus as default= -2 since it's faster than other ways.
It still took about 4.5s per image for validation.
I saw one posting that you said 'Only the neural network can use GPU. The thresholding and EM can only use CPU'.
does that mean validation only has to be worked with CPU? Can I know  the reason? 

Thank you

**Comment by teeinn** [comment]
I close my case since I understood how this system works

**Comment by VikasRajashekar** [comment]
Can you please explain what happens in validation? I see that no GPU is used.  @teeinn @javiribera

**Comment by javiribera** [comment]
During inference (either validation or testing), the probability map is converted to a binary mask using (1) static thresholding, (2) Otsu thresholding, or (3) a Beta Mixture Model-based thresholding, depending on the value of tau. Then Expectation Maximization is done to yield the final locations. This is all implemented in CPU.

**Comment by javiribera** [comment]
> I know there's been many issues related with validation time. But to me, it's not clear.
> 
> I am training mall dataset and set --taus as default= -2 since it's faster than other ways. It still took about 4.5s per image for validation. I saw one posting that you said 'Only the neural network can use GPU. The thresholding and EM can only use CPU'. does that mean validation only has to be worked with CPU? Can I know the reason?
> 
> Thank you

I am surprised to hear this. The fastest way should by static thresholding (with a tau between 0 and 1).
