### ISSUE TITLE
Small issue when using plants dataset

### ISSUE THREAD

**Issue by joaqo** [javiribera/locating-objects-without-bboxes#5]
When using the plant dataset, `object-locator/data.py` should have the following changes to prevent KeyErrors:

`dictionary['locations'] = eval(dictionary['locations'])`
to
`dictionary['locations'] = eval(dictionary['plant_locations'])`

and

`dictionary['count'] = torch.tensor([dictionary['count']], dtype=torch.get_default_dtype())`
to
`dictionary['count'] = torch.tensor([dictionary['plant_count']], dtype=torch.get_default_dtype())`

Didn't make a PR cause I thought you'd probably like to change it in some way that generalizes for all datasets that I am not aware of.

Cheers, thanks for the great repo!

**Comment by javiribera** [comment]
Thanks for the heads up! I will probably change the dataset to make it more general.

**Comment by javiribera** [comment]
I modified the keys in gt.csv in the plant datasets to "locations" and "count" instead of "plant_locations" and "plant_count". This way is more general and there is no need to modify the code. It shouldn't happen, but feel free to reopen this issue if you still experience this error.
